/// Flutter icons MisIconos2
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MisIconos2
///      fonts:
///       - asset: fonts/MisIconos2.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MisIconos2 {
  MisIconos2._();

  static const _kFontFam = 'MisIconos2';
  static const String? _kFontPkg = null;

  static const IconData reloj = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData config = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData doctor = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData glucosa = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData grafic = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menu = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phone = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData switch_icon = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
